name: Preparation
description: Preparation composite step for NodeJS
outputs:
    cache-hit:
        description: "Is cache hit"
        value: ${{ steps.cache.outputs.cache-hit }}
runs:
    using: "composite"
    steps:
        -   name: Set up Node.js
            uses: actions/setup-node@v3
            with:
                node-version: 18.14.2
        -   name: Restore node_modules cache
            id: cache
            uses: actions/cache/restore@v3
            with:
                path: node_modules
                key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}
        -   name: Install dependencies
            if: steps.cache.outputs.cache-hit != 'true'
            shell: bash
            run: npm ci
