name: Pulumi Destroy
on:
  workflow_dispatch:
  schedule:
    - cron: '55 10 * * *'
  delete:

jobs:
  cleanup:
    name: Cleanup
    runs-on: ubuntu-latest
    steps:
      - name: Exec
        env:
          GITHUB_EVENT_REF: ${{ github.event.ref }}
        run: |
          echo '${{ toJSON(github) }}'

      - name: Test cache
        uses: actions/cache@v3
        with:
          path: './README.md'
          key: stack
