name: Cleanup
on:
  delete
jobs:
  cleanup:
    name: Cleanup
    runs-on: ubuntu-latest
    steps:
      - name: Exec
        env:
          GITHUB_REF: ${{ github.event.ref }}
        run: |
          export STACK_NAME="dev-$(echo ${GITHUB_REF##*/} | sed 's/[^0-9]*//g')" 
          echo "${STACK_NAME}"
