name: Pull Request Checks
on:
    pull_request:
        types:
            - opened
            - synchronize
            - reopened
        branches:
            - main
            - WIP
jobs:
    check:
        name: Check
        uses: ./.github/workflows/quality_gate.yml

