name: Pulumi Deploy
on:
  push:
jobs:
  update:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Test cache
        uses: actions/cache@v3
        with:
          path: './README.md'
          key: stack

      - name: Exec
        env:
          GITHUB_EVENT_REF: ${{ github.event.ref }}
        run: |
          ls -la
