name: Pulumi Deploy
on:
  push:
jobs:
  update:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Exec
        env:
          GITHUB_EVENT_REF: ${{ github.event.ref }}
        run: |
          export STACK_NAME="dev-$(echo ${GITHUB_EVENT_REF##*/} | sed 's/[^0-9]*//g')" 
          echo "${STACK_NAME}"
