name: Quality Gate

on:
    workflow_call:

jobs:
    quality_gate:
        name: Quality Gate
        runs-on: arc-runner-set
        steps:
            -   name: Prepare runner
                run: |
                    sudo apt-get update -y
                    sudo apt-get install -y --no-install-recommends ca-certificates curl apt-transport-https lsb-release gnupg
                    curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
                    echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
                    sudo apt-get update -y
                    sudo apt-get install -y --no-install-recommends azure-cli
                    curl -fsSL https://deb.nodesource.com/setup_18.x | sudo bash -
                    sudo apt-get install -y --no-install-recommends nodejs
                    sudo rm -rf /var/lib/apt/lists/*
                    curl -fsSL https://get.pulumi.com | sh
            -   name: Checkout code
                uses: actions/checkout@v1
                with:
                    fetch-depth: 0
            -   name: Install dependencies
                id: prepare
                uses: ./.github/actions/prepare
            -   name: Run linter
                uses: ./.github/actions/node
                with:
                    run: |
                        npm run lint
            -   name: Run unit tests
                uses: ./.github/actions/node
                with:
                    run: |
                        npm run test:unit
            -   name: Save node_modules cache
                uses: actions/cache/save@v3
                if: steps.prepare.outputs.cache-hit != 'true'
                with:
                    path: node_modules
                    key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}
