name: Quality Gate

on:
    workflow_call:

jobs:
    quality_gate:
        name: Quality Gate
        runs-on: arc-runner-set
        env:
            NODE_MAJOR: 18
        steps:
            -   name: Prepare runner
                run: |
                    sudo apt-get update -y
                    sudo apt-get install -y --no-install-recommends ca-certificates curl apt-transport-https lsb-release gnupg git build-essential
                    curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
                    echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list
                    sudo apt-get update -y
                    sudo apt-get install -y --no-install-recommends nodejs
                    sudo rm -rf /var/lib/apt/lists/*
            -   name: Checkout code
                uses: actions/checkout@v1
                with:
                    fetch-depth: 0
            -   name: Install dependencies
                id: prepare
                uses: ./.github/actions/prepare
            -   name: Run linter
                uses: ./.github/actions/node
                with:
                    run: |
                        npm run lint
            -   name: Run unit tests
                uses: ./.github/actions/node
                with:
                    run: |
                        npm run test:unit
            -   name: Save node_modules cache
                uses: actions/cache/save@v3
                if: steps.prepare.outputs.cache-hit != 'true'
                with:
                    path: node_modules
                    key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}
